sudo: required
# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: xenial
language: python
python:
    # python versions used in el7 SCL & supported fedora
    - "3.6"
    - "3.7"
env:
    - TEST=pulp
    - TEST=docs
matrix:
  exclude:
    - python: "3.6"
      env: TEST=docs
  fast_finish: true
addons:
    # postgres versions provided by el7 RHSCL (lowest supportable version)
    postgresql: "9.6"
services:
    - postgresql
    - redis-server
install: source .travis/install.sh
before_script: source .travis/before_script.sh
script: source .travis/script.sh

stages:
  - name: test
  - name: deploy
    if: tag IS present
  - name: publish-beta-docs
    if: tag IS present
  - name: publish-nightly-docs
jobs:
  include:
  - stage: deploy
    script: skip
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: pulp
      password:
        secure: TsN92ZD/+l+Yxr93hB0cwsETwXtlf/qHUOOS+8nJAGwSxbkjY+9IzcJYGQnGlzy8RJ8rCbtnGDQEf0AmdtzlQ3QeGjLLkuQwOADe9rUqYlX1NPWmjj5UNoFkCnER5418tOu5w7ye4iRozBZUQfEZUAQCi0KiHK/oW8+0/seraGxHLHQdv6umBEjtsGP0xZ9V7KabIYCfq1jc8nkmydB2WInmCaCdVJXjn1dMVL57zC06zUbj2zDJYnjvdFtL1suC2eRMF7/Z1WOL2fmpgqXCD4tjFPJJ2RxOxe/BInsoAuqUebkyYPCQhSlBAhYnLj3foWI9i8ILMd7MkImWSb8FLpPvT08edCc5W3O/Pw0SfvQa22C/4kzITi1c7HfHSSTEyI6KQMseDdMKFUOxnGRZSd06nrtRFVnGIijoD3TEgEBr3rGEGLi5Xta/mRll5j6qf2JaStKjWKIhkxxiPl4qpEnnkOifVD48xgz90kvCziC94AaYxNrcES1nkqgnkY3A0jqeaxEN29VGUX9ZGlcib1DWWqf+KRpnXfg+chqhUzrwR34iQv7/fdCqTQyNrAJYGxXKo0ayMVKuB4CIU5B2bZXJVo96oMfS+O/rOj/T+1YyCCPqm+RspyE/yGdnj14ShO04lWMBL0O4/r2d7cdUS9gBht8a8bcuSFV88wOlqR8=
      on:
        tags: true
  - stage: publish-beta-docs
    script: bash .travis/publish_docs.sh rc
    env:
      - DJANGO_MAX=2.2.100
      - DB=postgres
      - TEST=docs
    if: tag IS present
  - stage: publish-nightly-docs
    script: bash .travis/publish_docs.sh nightly
    env:
      - DJANGO_MAX=2.2.100
      - DB=postgres
      - TEST=docs
    if: type != pull_request
